name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Inject env into index.html
        run: echo "<script>window.MY_ENV='${{ secrets.MY_ENV }}'</script>" >> index.html

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy
        uses: actions/deploy-pages@v4
